# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-18 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_books_app', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='liked_by',
            field=models.ManyToManyField(related_name='favorites', to='user_books_app.User'),
        ),
    ]
