# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-16 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='description',
            field=models.TextField(default='Weird stranger things are happening'),
            preserve_default=False,
        ),
    ]
